<?php
declare(strict_types=1);
if (! defined('ABSPATH')) { exit; }
final class Shakass_Settings {
 public static function install_defaults(): void { add_option('shakass_products', shakass_default_products()); add_option('shakass_mockups', shakass_default_mockups()); add_option('shakass_pricing', shakass_default_pricing()); add_option('shakass_settings', shakass_default_settings()); }
 public static function sanitize_products(array $rows): array { $out=[]; foreach ($rows as $row) { if (empty($row['name'])) continue; $colors=[]; foreach (preg_split('/\r\n|\r|\n/', (string)($row['colors'] ?? '')) as $line) { if (!trim($line)) continue; [$name,$hex]=array_pad(array_map('trim', explode('|',$line,2)),2,'#000000'); $colors[]=['name'=>sanitize_text_field($name),'hex'=>sanitize_hex_color($hex) ?: '#000000']; } $slug=sanitize_title($row['slug'] ?: $row['name']); $out[]=['name'=>sanitize_text_field($row['name']),'slug'=>$slug,'active'=>empty($row['active'])?0:1,'type'=>sanitize_text_field($row['type'] ?? 'T-shirt'),'description'=>sanitize_textarea_field($row['description'] ?? ''),'material'=>sanitize_text_field($row['material'] ?? ''),'weight'=>sanitize_text_field($row['weight'] ?? ''),'fit'=>sanitize_text_field($row['fit'] ?? 'Unisexe'),'sizes'=>array_values(array_filter(array_map('sanitize_text_field',(array)($row['sizes'] ?? [])))),'colors'=>$colors,'default'=>empty($row['default'])?0:1]; } if ($out && !array_filter($out, fn($p)=>!empty($p['default']))) $out[0]['default']=1; return $out ?: shakass_default_products(); }
 public static function sanitize_mockups(array $rows): array { $out=[]; foreach ($rows as $row) { if (empty($row['name'])) continue; $zone=function($prefix) use ($row){ return ['x'=>max(0,min(100,(float)($row[$prefix.'_x']??25))),'y'=>max(0,min(100,(float)($row[$prefix.'_y']??24))),'w'=>max(5,min(100,(float)($row[$prefix.'_w']??50))),'h'=>max(5,min(100,(float)($row[$prefix.'_h']??58)))];}; $out[]=['product'=>sanitize_title($row['product'] ?? ''),'name'=>sanitize_text_field($row['name']),'front_image'=>esc_url_raw($row['front_image'] ?? ''),'back_image'=>esc_url_raw($row['back_image'] ?? ''),'color'=>sanitize_hex_color($row['color'] ?? '#08090d') ?: '#08090d','active'=>empty($row['active'])?0:1,'front_zone'=>$zone('front'),'back_zone'=>$zone('back')]; } return $out ?: shakass_default_mockups(); }
 public static function sanitize_pricing(array $data): array { $pricing=shakass_default_pricing(); foreach ((array)($data['base']??[]) as $k=>$v) $pricing['base'][sanitize_title($k)]=(float)$v; foreach (['A7','A6','A5','A4','A3'] as $f) $pricing['formats'][$f]=(float)($data['formats'][$f]??$pricing['formats'][$f]); foreach (['text','image','qr'] as $k) $pricing[$k]=(float)($data[$k]??$pricing[$k]); foreach (['1-9','10-24','25-49','50+'] as $k) $pricing['discounts'][$k]=(float)($data['discounts'][$k]??$pricing['discounts'][$k]); return $pricing; }
 public static function sanitize_settings(array $data): array { $tools=[]; foreach (array_keys(shakass_active_tools()) as $tool) $tools[$tool]=empty($data['tools'][$tool])?0:1; return ['email'=>sanitize_email($data['email'] ?? get_option('admin_email')),'accent'=>sanitize_hex_color($data['accent'] ?? '#ff5a2c') ?: '#ff5a2c','dark_mode'=>empty($data['dark_mode'])?0:1,'cta'=>sanitize_text_field($data['cta'] ?? 'Envoyer ma demande'),'trust'=>sanitize_text_field($data['trust'] ?? ''),'default_product'=>sanitize_title($data['default_product'] ?? ''),'tools'=>$tools]; }
}
